name: "✨ Feature"
description: "새로운 기능 추가"
labels: "feature"
body:
  - type: textarea
    attributes:
      label: 📑 설명
      description: 개발할 새로운 기능에 대한 설명 작성
      validations:
        required: true
  - type: textarea
    attributes:
      label: ✅ 작업할 내용
      description: 작업할 내용을 소단위로 쪼개어 작성
      placeholder: "- [ ] 기능 꼴로 작성"
