spring:
  application:
    name: backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


#카카오 로그인 관련
kakao:
  client-id: ${KAKAO_API_KEY}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  client-secret: ${KAKAO_SECRET_CODE}

#jwt 토큰 관련
jwt:
  secret: ${JWT_SECRET}
  duration: ${JWT_VALID_TIME}